### ISSUE TITLE
Import error for cuequivariance_ops_torch even in a brand new conda env

### ISSUE THREAD

**Issue by ShaunHan** [ACEsuit/mace#1221]
Hi, I am facing some issues installing cuequivariance-ops-torch-cu12. I made a clean new Python 3.11 conda env and then `pip install torch cuequivariance cuequivariance-torch cuequivariance-ops-torch-cu12`. When I try to `import cuequivariance_ops_torch`, I get the following error:
```
Error while loading libcue_ops.so: libcublas.so.12: cannot open shared object file: No such file or directory
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/cuequivariance_ops_torch/__init__.py", line 16, in <module>
    from cuequivariance_ops_torch.segmented_transpose import (
  File "/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/cuequivariance_ops_torch/segmented_transpose.py", line 13, in <module>
    import cuequivariance_ops_torch._ext as ops
  File "/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/cuequivariance_ops_torch/_ext/__init__.py", line 12, in <module>
    from .cuequivariance_ops_torch_ext import *  # light-weight wrapper
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcue_ops.so: cannot open shared object file: No such file or directory
```
This is the same error when we first tried to install cuequivariance_ops_torch in our existing mace conda env. Does any one know what could be the reason for this error? I am using the NVIDIA H100 NVL GPU, and the glibc version is 2.34. Below is my `pip list`:
```
Package                       Version
----------------------------- ---------
cuequivariance                0.6.1
cuequivariance-ops-cu12       0.6.1
cuequivariance-ops-torch-cu12 0.6.1
cuequivariance-torch          0.6.1
filelock                      3.20.0
fsspec                        2025.9.0
Jinja2                        3.1.6
MarkupSafe                    3.0.3
mpmath                        1.3.0
networkx                      3.5
numpy                         2.3.3
nvidia-cublas-cu12            12.8.4.1
nvidia-cuda-cupti-cu12        12.8.90
nvidia-cuda-nvrtc-cu12        12.8.93
nvidia-cuda-runtime-cu12      12.8.90
nvidia-cudnn-cu12             9.10.2.21
nvidia-cufft-cu12             11.3.3.83
nvidia-cufile-cu12            1.13.1.3
nvidia-curand-cu12            10.3.9.90
nvidia-cusolver-cu12          11.7.3.90
nvidia-cusparse-cu12          12.5.8.93
nvidia-cusparselt-cu12        0.7.1
nvidia-ml-py                  13.580.82
nvidia-nccl-cu12              2.27.3
nvidia-nvjitlink-cu12         12.8.93
nvidia-nvtx-cu12              12.8.90
opt_einsum                    3.4.0
pip                           25.2
platformdirs                  4.5.0
pynvml                        13.0.1
scipy                         1.16.2
setuptools                    80.9.0
sympy                         1.14.0
torch                         2.8.0
tqdm                          4.67.1
triton                        3.4.0
typing_extensions             4.15.0
wheel                         0.45.1
```

**Comment by ilyes319** [comment]
Hello,

Can you open an issue to the cuequivariance repo directly and link that one so @mariogeiger can help.

**Comment by mariogeiger** [comment]
Hi

I think the error is
```
Error while loading libcue_ops.so: libcublas.so.12: cannot open shared object file: No such file or directory
```
Which probably means that it has trouble finding cublas version 12 on your environment. Can you try to update cublas? 
There is a pypi package for it: https://pypi.org/project/nvidia-cublas-cu12/

**Comment by ShaunHan** [comment]
Hi @mariogeiger I tried upgrading `nvidia-cublas-cu12` from 12.8.4.1 to 12.9.1.4, but I got the same error

**Comment by mariogeiger** [comment]
I guess somehow it struggles to locate it. Can you try playing with LD_LIBRARY_PATH maybe?

**Comment by ShaunHan** [comment]
Hi @mariogeiger, @ilyes319 I am able to fix the import error by `export LD_LIBRARY_PATH="$( find "$(python -c 'import site,sys; print(site.getsitepackages()[0])')" -type d -path '*/nvidia/*/lib' -print | tr '\n' ':' )$LD_LIBRARY_PATH"`. However, when I test CuEq on MACE, although I don't get any error, I got a lot of warnings and the speeed of running a relaxation task with CuEq is even slower than running without. Do you have any idea what might be the reason?

With CuEq:
```
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/e3nn/o3/_wigner.py:10: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  _Jd, _W3j_flat, _W3j_indices = torch.load(os.path.join(os.path.dirname(__file__), 'constants.pt'))
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/mace/calculators/mace.py:197: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  torch.load(f=model_path, map_location=device)
Using head default out of ['pt_head', 'default']
Converting models to CuEq for acceleration
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/mace/modules/models.py:84: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  "atomic_numbers", torch.tensor(atomic_numbers, dtype=torch.int64)
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/cuequivariance_torch/primitives/segmented_polynomial.py:147: UserWarning: Hello! It looks like you're using code that was written for an older version of this library.
Starting in v0.6.0, the `method` argument is suggested when using `SegmentedPolynomial()`.
This change helps ensure you get optimal performance by explicitly choosing the computation method.
For the moment, we will default to the 'uniform_1d' method.

To remove this warning, add a `method` parameter to your function call. Here are the available options:
• 'naive' - Works everywhere but not optimized (good for testing)
• 'uniform_1d' - Fast CUDA implementation for single uniform mode polynomials
• 'fused_tp' - A more general CUDA implementation, supporting many 3 and 4 operands contractions.
• 'indexed_linear' - A CUDA implementation for linear layers with indexed weights.

  warnings.warn(
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/cuequivariance_torch/primitives/segmented_polynomial.py:147: UserWarning: Hello! It looks like you're using code that was written for an older version of this library.
Starting in v0.6.0, the `method` argument is suggested when using `SegmentedPolynomial()`.
This change helps ensure you get optimal performance by explicitly choosing the computation method.
For the moment, we will default to the 'uniform_1d' method.

To remove this warning, add a `method` parameter to your function call. Here are the available options:
• 'naive' - Works everywhere but not optimized (good for testing)
• 'uniform_1d' - Fast CUDA implementation for single uniform mode polynomials
• 'fused_tp' - A more general CUDA implementation, supporting many 3 and 4 operands contractions.
• 'indexed_linear' - A CUDA implementation for linear layers with indexed weights.

      Step     Time          Energy          fmax
BFGS:    0 09:25:20    -1979.272357        5.878684
...
BFGS:  288 09:26:00    -2018.030579        0.008961
```

Without CuEq:
```
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/e3nn/o3/_wigner.py:10: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  _Jd, _W3j_flat, _W3j_indices = torch.load(os.path.join(os.path.dirname(__file__), 'constants.pt'))
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/mace/calculators/mace.py:197: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  torch.load(f=model_path, map_location=device)
Using head default out of ['pt_head', 'default']

      Step     Time          Energy          fmax
BFGS:    0 09:21:33    -1979.272357        5.878684
...
BFGS:  288 09:22:10    -2018.030579        0.008961
```

**Comment by ilyes319** [comment]
Can you update to latest main to remove the warning, we fixed that.

**Comment by ShaunHan** [comment]
Hi @ilyes319 I'm able to get rid of the warnings after updating. However, there seems to still be no CuEq acceleration in relaxation jobs using MACE. Is this normal? Does the CuEq acceleration only works for certain tasks?

**Comment by ilyes319** [comment]
what model are you using?

**Comment by ShaunHan** [comment]
I'm using a finetuned MACE model (finetuned from MACE-MPA-0 on our custom high-entropy alloy DFT dataset)

**Comment by ilyes319** [comment]
mmmm maybe the ASE overhead are too big to observe speed up. What system size are you testing? What gpu?

**Comment by ShaunHan** [comment]
255 atoms, NVIDIA H100 NVL GPU
