### ISSUE TITLE
On multiply GPUs, the code fails in evaluation after training

### ISSUE THREAD

**Issue by gitlzzz** [ACEsuit/mace#1348]
When training on multiple GPU nodes, the evaluation of second-stage checkpoints fails, and the .model file is not generated.

The process stops at
```
2026-01-27 01:49:24.365 INFO: Loading checkpoint: ./checkpoints/MACE_run-1_epoch-224.pt
2026-01-27 01:49:24.441 INFO: Loaded Stage one model from epoch 224 for evaluation
2026-01-27 01:49:24.441 INFO: Saving model to checkpoints/MACE_run-1.model
2026-01-27 01:49:24.631 INFO: Compiling model, saving metadata to MACE_compiled.model
2026-01-27 01:49:25.455 INFO: Computing metrics for training, validation, and test sets
2026-01-27 01:49:25.456 INFO: Skipping evaluation for heads: ['pt_head']
2026-01-27 01:49:25.456 INFO: Evaluating train_Default ...
2026-01-27 01:57:00.345 INFO: Evaluating valid_Default ...
2026-01-27 01:57:01.547 INFO: Error-table on TRAIN and VALID:
+---------------+---------------------+------------------+-------------------+
|  config_type  | RMSE E / meV / atom | RMSE F / meV / A | relative F RMSE % |
+---------------+---------------------+------------------+-------------------+
| train_Default |           13.5      |        148.0     |         10.71     |
| valid_Default |           13.5      |        164.2     |         11.32     |
+---------------+---------------------+------------------+-------------------+
2026-01-27 01:57:01.547 INFO: Evaluating Default_Default ...
2026-01-27 01:57:02.432 INFO: Error-table on TEST:
+-----------------+---------------------+------------------+-------------------+
|   config_type   | RMSE E / meV / atom | RMSE F / meV / A | relative F RMSE % |
+-----------------+---------------------+------------------+-------------------+
| Default_Default |            6.2      |          3.9     |        857.26     |
+-----------------+---------------------+------------------+-------------------+
```

The error is
```
[rank8]:[E127 02:18:02.782372100 ProcessGroupNCCL.cpp:629] [Rank 8] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=372981, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600004 milliseconds before timing out.
[rank8]:[E127 02:18:02.783190013 ProcessGroupNCCL.cpp:2168] [PG ID 0 PG GUID 0(default_pg) Rank 8]  failure detected by watchdog at work sequence id: 372981 PG status: last enqueued work: 372981, last completed work: 372980
[rank8]:[E127 02:18:02.783228618 ProcessGroupNCCL.cpp:667] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank8]:[E127 02:18:02.783233487 ProcessGroupNCCL.cpp:681] [Rank 8] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank8]:[E127 02:18:02.783237305 ProcessGroupNCCL.cpp:695] [Rank 8] To avoid data inconsistency, we are taking the entire process down.
[rank2]:[E127 02:18:02.494505730 ProcessGroupNCCL.cpp:629] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=372981, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600010 milliseconds before timing out.
[rank7]:[E127 02:18:02.641241539 ProcessGroupNCCL.cpp:629] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=372981, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600013 milliseconds before timing out.
[rank13]:[E127 02:18:02.602675298 ProcessGroupNCCL.cpp:629] [Rank 13] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=372981, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600015 milliseconds before timing out.
[rank15]:[E127 02:18:02.603245911 ProcessGroupNCCL.cpp:629] [Rank 15] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=372981, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600016 milliseconds before timing out.
[rank13]:[E127 02:18:02.603610036 ProcessGroupNCCL.cpp:2168] [PG ID 0 PG GUID 0(default_pg) Rank 13]  failure detected by watchdog at work sequence id: 372981 PG status: last enqueued work: 372981, last completed work: 372980
[rank13]:[E127 02:18:02.603632389 ProcessGroupNCCL.cpp:667] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank13]:[E127 02:18:02.603636587 ProcessGroupNCCL.cpp:681] [Rank 13] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank13]:[E127 02:18:02.603639563 ProcessGroupNCCL.cpp:695] [Rank 13] To avoid data inconsistency, we are taking the entire process down.
[rank15]:[E127 02:18:02.604091777 ProcessGroupNCCL.cpp:2168] [PG ID 0 PG GUID 0(default_pg) Rank 15]  failure detected by watchdog at work sequence id: 372981 PG status: last enqueued work: 372981, last completed work: 372980
[rank15]:[E127 02:18:02.604122958 ProcessGroupNCCL.cpp:667] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank15]:[E127 02:18:02.604129380 ProcessGroupNCCL.cpp:681] [Rank 15] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank15]:[E127 02:18:02.604134810 ProcessGroupNCCL.cpp:695] [Rank 15] To avoid data inconsistency, we are taking the entire process down.
[rank2]:[E127 02:18:02.507364110 ProcessGroupNCCL.cpp:2168] [PG ID 0 PG GUID 0(default_pg) Rank 2]  failure detected by watchdog at work sequence id: 372981 PG status: last enqueued work: 372981, last completed work: 372980
[rank2]:[E127 02:18:02.507408336 ProcessGroupNCCL.cpp:667] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank2]:[E127 02:18:02.507413827 ProcessGroupNCCL.cpp:681] [Rank 2] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank2]:[E127 02:18:02.507417463 ProcessGroupNCCL.cpp:695] [Rank 2] To avoid data inconsistency, we are taking the entire process down.
[rank8]:[E127 02:18:02.804184833 ProcessGroupNCCL.cpp:1895] [PG ID 0 PG GUID 0(default_pg) Rank 8] Process group watchdog thread terminated with exception: [Rank 8] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=372981, OpType=ALLREDUCE,
NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600004 milliseconds before timing out
```

Another issue with an identified cause, for your reference: A similar issue arises when patience is triggered with training on multiple GPUs (within a single node). In this case, the code fails to proceed to the second stage and instead becomes stuck while loading the first-stage checkpoint.
```
2025-12-12 07:53:11.184 INFO: Epoch 98: head: Default, loss=0.00148793, RMSE_E_per_atom= 6.60 meV, RMSE_F= 63.04 meV / A
2025-12-12 07:53:41.557 INFO: Epoch 99: head: Default, loss=0.00150423, RMSE_E_per_atom= 5.69 meV, RMSE_F= 63.86 meV / A
2025-12-12 07:53:41.557 INFO: Training complete
2025-12-12 07:53:41.557 INFO:
2025-12-12 07:53:41.557 INFO: ===========RESULTS===========
2025-12-12 07:53:41.561 INFO: Loading checkpoint: ./checkpoints/MACE_run-1_epoch-7.pt
```
with error:
```
/conda/mace/lib/python3.10/site-packages/torch/distributed/utils.py", line 294, in _verify_param_shape_across_processes
[rank0]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank0]: RuntimeError: Detected mismatch between collectives on ranks. Rank 0 is running collective: CollectiveFingerPrint(SequenceNumber=633704, OpType=ALLGATHER, TensorShape=[1], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default
), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))), but Rank 1 is running collective: CollectiveFingerPrint(SequenceNumber=0OpType=REDUCE).Collectives differ in the following aspects: Sequence number: 633704vs 0 Op type: ALLGATHERvs REDUCE
Tensor Tensor shapes: 1vs Tensor Tensor dtypes: Longvs Tensor Tensor devices: TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))vs
[rank1]: Traceback (most recent call last):
```

The analysis from the IT suggests a bug in the code for the latter case:

```
Rank 0 is here, setting up for the SWA phase of training: https://github.com/ACEsuit/mace/blob/v0.3.13/mace/cli/run_train.py#L888

But the other ranks are stuck earlier, still in the main train function, at this barrier: https://github.com/ACEsuit/mace/blob/v0.3.13/mace/tools/train.py#L328

This is obviously odd, and I think it's due to a bug in the mace code. I noticed that in that train function, there is a code block executed by rank-0 only which contains a break for the training patience criteria: https://github.com/ACEsuit/mace/blob/v0.3.13/mace/tools/train.py#L298

This breaks rank 0 out of the training loop and bypasses the barrier that the other ranks get stuck at.
```

MACE version: 0.3.13
CUDA version: 12.4

**Comment by ilyes319** [comment]
Hey @gitlzzz can you try the mace main branch and see if it is solved?

**Comment by gitlzzz** [comment]
Hi, @ilyes319, I have tried the main branch of mace 0.3.15 now, it seems the patience issue fixed, but the training on multiple GPU nodes still failed with the same error.

```
[rank15]:[E130 22:43:25.201174658 ProcessGroupNCCL.cpp:607] [Rank 15] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=31662, OpType=ALLREDUCE, NumelIn=1, NumelOut=1
, Timeout(ms)=600000) ran for 600006 milliseconds before timing out.
[rank7]:[E130 22:43:25.045931790 ProcessGroupNCCL.cpp:607] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=31662, OpType=ALLREDUCE, NumelIn=1, NumelOut=1,
Timeout(ms)=600000) ran for 600011 milliseconds before timing out.
[rank7]:[E130 22:43:25.046496651 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 7] Exception (either an error or timeout) detected by watchdog at work: 31662, last enqueued N
CCL work: 31662, last completed NCCL work: 31661.
[rank7]:[E130 22:43:25.046513304 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 7] Timeout at NCCL work: 31662, last enqueued NCCL work: 31662, last completed NCCL work: 3166
1.
[rank7]:[E130 22:43:25.046521800 ProcessGroupNCCL.cpp:621] [Rank 7] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU
operations might run on corrupted/incomplete data.
[rank7]:[E130 22:43:25.046525597 ProcessGroupNCCL.cpp:627] [Rank 7] To avoid data inconsistency, we are taking the entire process down.
[rank15]:[E130 22:43:25.208280812 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 15] Exception (either an error or timeout) detected by watchdog at work: 31662, last enqueued
 NCCL work: 31662, last completed NCCL work: 31661.
[rank15]:[E130 22:43:25.208300019 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 15] Timeout at NCCL work: 31662, last enqueued NCCL work: 31662, last completed NCCL work: 31
661.
[rank15]:[E130 22:43:25.208306742 ProcessGroupNCCL.cpp:621] [Rank 15] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GP
U operations might run on corrupted/incomplete data.
[rank15]:[E130 22:43:25.208309898 ProcessGroupNCCL.cpp:627] [Rank 15] To avoid data inconsistency, we are taking the entire process down.
[rank7]:[E130 22:43:25.051346162 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 7] Process group watchdog thread terminated with exception: [Rank 7] Watchdog caught collectiv
e operation timeout: WorkNCCL(SeqNum=31662, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600011 milliseconds before timing out.
```

**Comment by ilyes319** [comment]
Dear @gitlzzz usually these kind of time out errors are because you did not setup the NCCL communication properly. Do you use a slurm cluster? you might want to ask your support.

**Comment by gitlzzz** [comment]
Hi @ilyes319, thank you for the response. Yes, I am using a slurm cluster. I will contact them.
