### ISSUE TITLE
LAMMPS-MACE requires extreme amounts of memory

### ISSUE THREAD

**Issue by beckobert** [ACEsuit/mace#229]
**Describe the bug**
When running MD for a 64-molecule water box with PBC on LAMMPs using mace pair style, my GPU runs out of memory (RTX 3090 Ti, 24GB), after initializing the simulation, when starting the dynamics.
The training was run on the same GPU without problems and `eval_configs.py` runs without problems and a memory requirement of around 2GB with batch_size=1.
I tried to run MD for a Zundel cation in LAMMPS, to check if my installation is broken, and it ran without problems and a memory usage of ~2GB.

**To Reproduce**
Here is my LAMMPS input script:
> #use variables to have settings in one place and for consistency
> variable dt      equal 0.0005
> variable T       equal 300.0
> variable tau_T   equal 100.0
> variable s_trj   equal 4
> variable n_run   equal 20000
> 
> #set the units to use as "metal" (eV, ps, Angstrom)
> units            metal
> atom_style       atomic
> atom_modify      map yes
> newton           on
> 
> boundary p p p
> read_data structure.data
> 
> pair_style       mace no_domain_composition
> pair_coeff       * * mace.pt H O
> 
> mass             1 1.008   # H
> mass             2 15.999  # O
> velocity         all create ${T} 42 dist gaussian
> neighbor         1.0 bin
> neigh_modify     every 1 delay 0 check yes
> timestep         ${dt}
> fix              nvt all nvt temp ${T} ${T} ${tau_T} tchain 3
> 
> run              ${n_run}
> 
> write_data       data.final

**Expected behavior**
LAMMPS runs the MD with memory requirements comparable to `eval_configs.py`.

**Setup**
 - Python: 3.10
 - MACE: 0.3.0
 - Cuda: 11.8
 - PyTorch: 2.1.1
 - cudnn: 8.7.0

**Additional context**
I built LAMMPS mostly according to the instructions, but with `BUILD_OMP=no` and `Kokkos_ENABLE_OPENMP=no`, as these settings led to some issues during compilation.

If you have any suggestions of what I could have done wrong, please let me know.

**Comment by wcwitt** [comment]
Hi - thanks for reporting.

> I tried to run MD for a Zundel cation in LAMMPS, to check if my installation is broken, and it ran without problems and a memory usage of ~2GB.

Thanks, this was a good test. Do smaller PBC water simulations work?

Can you also try without the neighbor and neigh_modify commands?

**Comment by beckobert** [comment]
Thank you for the quick response.

Yes, PBC calculations with small systems work, but they still require an unusually high amount of memory. A zundel cation in a 5x5x5 Angstrom^3 box and PBC requires 16GB of memory.

Initially, I used a model with my own parameters, but now I have also tried to run a model trained with the parameters from your [example](https://mace-docs.readthedocs.io/en/latest/examples/training_examples.html#liquid-water) and this now barely fits in my GPU memory (23.5GB of 24GB). But this is still 15x more than the 1.5GB I need to run this model with `eval_configs.py`. Do you have some benchmarks for this water model in LAMMPS to compare them with?

Commenting out the neighbor and neigh_modify commands have only a negligible effect.

Yet, I do have the feeling that the problem has something to do with the neighbor lists.
During training, MACE reports 

 > Average number of neighbors: 88.32208251953125

but during LAMMPS MD, I get 

> Total # of neighbors = 177186
> Ave neighs/atom = 922.84375

Even for the above-mentioned zundel with PBC test, I have a lot of neighbors for a system with rather low density.

> Total # of neighbors = 3688
> Ave neighs/atom = 526.85714
 
These numbers are also a lot higher when I compared them with simulations I ran using LAMMPS and NequIP, even though I would expect NequIP to have a much larger field of view and therefore a higher number of neighbors to consider.

**Comment by wcwitt** [comment]
Hi - any progress in understanding this?

On the following, I should note that the MACE-reported neighbors only includes those in the first cutoff sphere, whereas the LAMMPS number comes from the LAMMPS neighbor list, which is generated using (roughly) twice the small cutoff for num_interactions=2. So the numbers won't be the same, but something still seems wrong. Could it be a units issue?

> Yet, I do have the feeling that the problem has something to do with the neighbor lists.
During training, MACE reports
Average number of neighbors: 88.32208251953125
but during LAMMPS MD, I get
Total # of neighbors = 177186
Ave neighs/atom = 922.84375

You also might consider reducing your cutoff until the MACE-reported neighbors is closer to 30.

**Comment by beckobert** [comment]
Thank you for the suggestions, but unfortunately, nothing has helped so far.
It is the same input script as the one I have used for NequIP calculations, except for changes in the pair style (obviously) and the changes suggested in the [documentation](https://mace-docs.readthedocs.io/en/latest/guide/lammps.html), so I am quite confident that the set-up is reasonable.

The positions in my training data are in Angstrom, the energies in eV and the forces in eV/Angstrom, so the unit setting `metal` in LAMMPS should be correct, unless there is some automatic unit conversion in LAMMPS, that I am unaware of.

My r_max is 6 Angstrom, which is the same as in the example settings for a water model in the documentation, so I would hope that this is not too much.

**Comment by ilyes319** [comment]
Can you paste your log file for training the model?
Also does running ASE MD work fine?

**Comment by gabor1** [comment]
how many interaction layers are you using with MACE ? we typically use 2.

**Comment by beckobert** [comment]
Here is the log from the training. Something went wrong with the SWA at the end (I assume because of the low number of swa epochs, but that shouldn't be a problem, since I use the pre-swa model): [mace.log](https://github.com/ACEsuit/mace/files/13418064/mace.log)

I tested the ase calculator as described in the documentation (with my own model and configuration file, of course) and it worked perfectly fine with very low memory usage and much faster than LAMMPS. But I don't know how to access more detailed logs.

So far I have always used 2 interaction layers for my models.

**Comment by beckobert** [comment]
I have also tested my LAMMPS installation with some Lennard-Jones pair style  and everything worked perfectly fine.

**Comment by wcwitt** [comment]
I found the problem - there's a typo in the pair_style line.

> pair_style mace no_domain_composition

Should be `no_domain_decomposition`.

I'll tweak things so that the input is checked more carefully such that this can't happen.

To summarize: the 922 neighs/atom is about right for an effective interaction range of 6+6+2 Ang, where 2 is the skin distance. That is a bit high (and you might consider reducing your r_max slightly), but the main problem is that without `no_domain_decomposition` the ghost atoms are all treated as independent and the memory requirement is much higher.

**Comment by wcwitt** [comment]
No worries, thanks for sticking with it. It's a good reminder for us to sanitize the input, or someone else will surely have the same problem.
