### ISSUE TITLE
Runtime error : CUDA initialization?

### ISSUE THREAD

**Issue by jungsdao** [ACEsuit/mace#248]
**Describe the bug**
While I was trying to run optimization with MACE + cuda, I have encountered this error. 
I found this error quite weird, because the same command works pretty well within VScode, but it gives error when I execute command in command line as `python **.py`. 
Could anyone give some advice why this happens and possible solutions?
Many thanks in advance :)

```
/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/fit/error.py:208: UserWarning: Missing reference or calculated property 'forces', 325 times
  warnings.warn(f"Missing reference or calculated property '{missed_prop}', {count} times")
/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/utils.py:130: UserWarning: Using random root seed 774872388 for <function _run_autopara_wrappable at 0x7fc9cc1d8680>
  warnings.warn(f"Using random root seed {root_global_seed} for {label}")
Running wfl.generate.optimize._run_autopara_wrappable with num_python_subprocesses=1, num_inputs_per_python_subprocess=40
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/pool.py", line 59, in _wrapped_autopara_wrappable
    outputs = op(*u_args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/generate/optimize.py", line 85, in _run_autopara_wrappable
    calculator = construct_calculator_picklesafe(calculator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/utils/parallel.py", line 51, in construct_calculator_picklesafe
    return calculator[0](*c_args, **c_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/mace/calculators/mace.py", line 112, in __init__
    self.models = [
                  ^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/mace/calculators/mace.py", line 113, in <listcomp>
    torch.load(f=model_path, map_location=device) for model_path in model_paths
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/serialization.py", line 1083, in restore_location
    return default_restore_location(storage, map_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/serialization.py", line 163, in validate_cuda_device
    device = torch.cuda._utils._get_device_index(location, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/cuda/_utils.py", line 36, in _get_device_index
    return _torch_get_device_index(device, optional, allow_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/_utils.py", line 729, in _get_device_index
    device_idx = _get_current_device_index()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/_utils.py", line 668, in _get_current_device_index
    return _get_device_attr(lambda m: m.current_device())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/_utils.py", line 659, in _get_device_attr
    return get_member(torch.cuda)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/_utils.py", line 668, in <lambda>
    return _get_device_attr(lambda m: m.current_device())
                                      ^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: initialization error
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/home/hjung/Calculation/4_Free_energy_calculation/1_Rh/0_CHO/batch_gap_fit.py", line 758, in <module>
    main(ecutwfc = ecutwfc, cv_range = args.cv_range, verbose=True)
  File "/work/home/hjung/Calculation/4_Free_energy_calculation/1_Rh/0_CHO/batch_gap_fit.py", line 581, in main
    run_optimize(initial_structures[i], outfiles[i], files["mace"], **optimize_params)
  File "/work/home/hjung/Calculation/4_Free_energy_calculation/1_Rh/0_CHO/batch_gap_fit.py", line 207, in run_optimize
    optimize(in_config, out_config, calculator=calculator,
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/generate/optimize.py", line 207, in optimize
    return autoparallelize(_run_autopara_wrappable, *args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/base.py", line 177, in autoparallelize
    return _autoparallelize_ll(autopara_info, inputs, outputs, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/base.py", line 225, in _autoparallelize_ll
    out = do_in_pool(autopara_info.num_python_subprocesses, autopara_info.num_inputs_per_python_subprocess,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/pool.py", line 153, in do_in_pool
    for result_group in results:
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
RuntimeError: CUDA error: initialization error
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - MACE version : 0.3.0
 - Pytorch version : 2.0.1
 
**Additional context**

**Comment by ilyes319** [comment]
Does it work if you try to run on CPU only?

**Comment by jungsdao** [comment]
Thanks for prompt comment :)
When I change to CPU only, then I get different error like following

```
Traceback (most recent call last):
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/pool.py", line 59, in _wrapped_autopara_wrappable
    outputs = op(*u_args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/descriptors/mace_desc.py", line 56, in _calc_autopara_wrappable
    descriptor = np.average(calculator.get_descriptors(at), axis=0)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/mace/calculators/mace.py", line 309, in get_descriptors
    descriptors = [model(batch.to_dict())["node_feats"] for model in self.models]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/mace/calculators/mace.py", line 309, in <listcomp>
    descriptors = [model(batch.to_dict())["node_feats"] for model in self.models]
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/mace/modules/models.py", line 366, in forward
    forces, virials, stress = get_outputs(
                              ^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/mace/modules/utils.py", line 135, in get_outputs
    compute_forces(energy=energy, positions=positions, training=training),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/mace/modules/utils.py", line 26, in compute_forces
    gradient = torch.autograd.grad(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unable to handle autograd's threading in combination with fork-based multiprocessing. See https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/home/hjung/Calculation/4_Free_energy_calculation/1_Rh/0_CHO/batch_gap_fit.py", line 746, in <module>
    main(ecutwfc = ecutwfc, cv_range = args.cv_range, verbose=True)
  File "/work/home/hjung/Calculation/4_Free_energy_calculation/1_Rh/0_CHO/batch_gap_fit.py", line 609, in main
    get_descriptors(ten_windows, files["desc"], files["mace"])
  File "/work/home/hjung/Calculation/4_Free_energy_calculation/1_Rh/0_CHO/batch_gap_fit.py", line 331, in get_descriptors
    desc_calc(in_config, out_config, calculator, key, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/descriptors/mace_desc.py", line 66, in calculate
    return autoparallelize(_calc_autopara_wrappable, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/base.py", line 177, in autoparallelize
    return _autoparallelize_ll(autopara_info, inputs, outputs, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/base.py", line 225, in _autoparallelize_ll
    out = do_in_pool(autopara_info.num_python_subprocesses, autopara_info.num_inputs_per_python_subprocess,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/site-packages/wfl/autoparallelize/pool.py", line 153, in do_in_pool
    for result_group in results:
  File "/home/hjung/miniforge3/envs/mace_env/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
RuntimeError: Unable to handle autograd's threading in combination with fork-based multiprocessing. See https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork
```

**Comment by jungsdao** [comment]
I was using wfl package's autoparalize function with this. But this was solved by adding following lines to the code. 
```
import torch.multiprocessing as mp
mp.set_start_method('spawn', force=True)
```

**Comment by ilyes319** [comment]
ok perfect!
